# define a makefile variable for the java compiler (Borrowed from http://www.cs.swarthmore.edu/~newhall/unixhelp/howto_makefiles.html)
#
JCC = javac

# define a makefile variable for compilation flags
# the -g flag compiles with debugging information
#
JFLAGS = -g

# typing 'make' will invoke the first target entry in the makefile 
# (the default one in this case)
#
default: Tree.class TreeNode.class MyTreeNode.class MyTree.class MyTreeTester.class F1To8.class Node.class F1To8Tester.class F1To8Interface.class

Record.class: Record.java
        $(JCC) $(JFLAGS) Record.java

RecordManager.class: RecordManager.java
        $(JCC) $(JFLAGS) RecordManager.java

RecordTester.class: RecordTester.java
        $(JCC) $(JFLAGS) RecordTester.java
             
# To start over from scratch, type 'make clean'.  
# Removes all .class files, so that the next make rebuilds them
#
clean: 
        $(RM) *.class